### PR TITLE
Fixes issue with color scale changing #249

### PR DESCRIPTION
**Pull request by spaghettikinase**
Small oversight in the logic.

### CODE REVIEW

**Comment by zakandrewking** [comment]
Now I am seeing this issue:

screen shot 2018-02-12 at 1 26 32 pm

Notice how the scale and the colors do not match up.

You can recreate it by loading the Escher dev server and loading this dataset:

https://github.com/zakandrewking/escher/blob/master/docs/_static/example_data/reaction_data_iJO1366.json

I'm not sure if it's related to this PR though. If not, feel free to open another one.

**Comment by spaghettikinase** [comment]
It's probably something to do with the picker location not tracking the
color correctly. I'll check it out tomorrow.

**Comment by spaghettikinase** [comment]
I can't replicate this. How did you get this to happen?

**Comment by spaghettikinase** [comment]
Alright this should fix it. Turns out I forgot to include functionality for going from stat type to value type.

**Pull request merged**
