### PR TITLE
Data series visualization

### PR DESCRIPTION
**Pull request by PathakAnkit**
- When data with more than 1 column is loaded, a slider initiates aiding in switching between data columns.

TODO
- [ ] Text for data.
- [x] An option to compare any two columns.
- [x] Data stats.

### CODE REVIEW

**Comment by zakandrewking** [comment]
this is a great start!

I was thinking: It would also be cool to provide statistics next to the slider, like the number of datasets (columns) and data points (rows).

And we should add a white background for the slider, as in the search box.

**Comment by Pathaked** [comment]
Okay sir, onto it. Also, should I provide metabolites and reactions/genes with different sliders as both can be loaded together?
On 22-Aug-2016 22:11, "Zachary A. King" <notifications@github.com> wrote:this is a great start!

I was thinking: It would also be cool to provide statistics next to the slider, like the number of datasets (columns) and data points (rows).

And we should add a white background for the slider, as in the search box.

**Comment by zakandrewking** [comment]
Yes, great idea

**Comment by zakandrewking** [comment]
I just pulled the latest code. A couple comments:

- The new UI pops up when you load a dataset, but not when the dataset is included at launch (e.g. 

```javascript
escher.Builder(map, null, null, sel, { reaction_data: my_data_obj })
```

- I was talking to potential users today, and I realized how cool it would be if the slider also worked during comparison mode. For instance, I would activate comparison mode with the checkbox, select one data series as the "control", and then slide to choose the "target" data series.

(pls feel free to ask me for more explanation :)

**Pull request closed without merging**
